# Generated by Django 6.1 on 2026-08-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("date", models.DateField(auto_now_add=True)),
                ("published", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
