# Generated by Django 6.1 on 2026-09-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [("can_unpublish_blog", "Может отменять публикацию поста")],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
