# Generated by Django 6.1 on 2026-08-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
