# Generated by Django 6.1 on 2026-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
