# Generated by Django 6.1 on 2026-08-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default=0, upload_to="products/"),
            preserve_default=False,
        ),
    ]
