# Generated by Django 6.1 on 2026-09-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_product_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_unpublish_product", "Может отменить публикацию продукта")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
